services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: django_db
            MYSQL_USER: django
            MYSQL_PASSWORD: djangopassword
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/workspace
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_NAME=django_db
            - DB_USER=django
            - DB_PASSWORD=djangopassword
        networks:
            - default

volumes:
    db_data:
        driver: local

networks:
    default:
        driver: bridge
